version: '3.8'

services:
  backend:
    build:
      context: ./  # Use project root
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://ai-db_owner:pDSKWljYuy39@ep-restless-sea-a5l3f205.us-east-2.aws.neon.tech/ai-db?sslmode=require"
    depends_on:
      - client
    volumes:
      - ./backend:/app  # Map only the backend directory
    command: ["/app/entrypoint.sh"]

  client:
    build:
      context: ./  # Use project root
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    command: ["npm", "run", "dev", "--", "--host"]