# Generated by Django 5.1.3 on 2024-11-24 17:46

import django.db.models.deletion
import lesson.custom
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlans',
            fields=[
                ('id', lesson.custom.UUID_field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_price_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duration', models.CharField(choices=[('weekly', 'weekly'), ('annualy', 'annualy'), ('monthly', 'monthly')], max_length=20)),
                ('features', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', lesson.custom.UUID_field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField(max_length=5)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending')], default='pending', max_length=40)),
                ('payment_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentplans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomers',
            fields=[
                ('id', lesson.custom.UUID_field(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(max_length=200)),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('canceled', 'canceled'), ('expired', 'expired'), ('past_due', 'past_due')], max_length=20)),
                ('current_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan', to='payment.paymentplans')),
            ],
        ),
    ]
