# Generated by Django 5.1.3 on 2024-11-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_stripecustomers_user_alter_paymentplans_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplans',
            name='stripe_product_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentplans',
            name='stripe_price_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stripecustomers',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('canceled', 'canceled'), ('expired', 'expired'), ('past_due', 'past_due')], default='inactive', max_length=20),
        ),
    ]
